Line Functionality added
omeryousaf/image-editor-for-ui-feedback pull request #18
Opened 2022-12-14 08:56 UTC by Shapokhan

fixes #17

2023-01-05 10:17 UTC, omeryousaf requested changes

2023-01-05 10:20 UTC, omeryousaf commented on src/CommentLine.js
> +    const [offsetFromElementInitialLeft, setOffsetFromElementInitialLeft] = useState(null)
@Shapokhan can we improve these names ? By `offsetFromElementInitialLeft` do u mean clicked point's left offset from the line start ?

2023-01-09 09:46 UTC, Shapokhan commented on src/Feedback.js
> +    const updatedInitalLeftOffset =
Updating positions code moved to Line Component.

2023-01-09 09:50 UTC, Shapokhan commented on src/CommentLine.js
> +import React, { useState } from "react";
Done.

2023-01-09 09:54 UTC, Shapokhan commented on src/CommentLine.js
> +    const [offsetFromElementInitialLeft, setOffsetFromElementInitialLeft] = useState(null)
This is actually the difference between clicked point and the line starting point. I have changed these states to global variables and named them like "diffInInitialLeft, diffInitialTop".

2023-01-11 09:56 UTC, omeryousaf approved these changes

2023-01-11 09:56 UTC, merged