Image modal implementation with proceed and discord option
omeryousaf/image-editor-for-ui-feedback pull request #36
Opened 2023-06-05 08:35 UTC by Shapokhan

fixes #31

2023-06-05 08:37 UTC, Shapokhan commented
@omeryousaf kindly have a look at this pull request. Let me know if it needs any changes or code improvement.

2023-06-14 09:16 UTC, omeryousaf commented on src/components/Modal/Modal.js
> +      <div className={classes.modalHeader}>
@Shapokhan can pass the modal header text from parent component so that we can later use this modal to ask a different question to a user ?

2023-06-14 09:21 UTC, omeryousaf commented on src/components/Modal/Modal.js
> +        <img src={props.modalInfo.imageUrl} alt="Resource not found" />
@Shapokhan can we pass html/jsx from parent as a prop so that the main content of this modal can change depending on which parent component calls it ? E.g. from Feedback component we call it to confirm new image upload but we might want to ask user to confirm on deleting something as well, e.g. if he deletes a line (just an example), we might want to ask him to confirm it. So in that case we might not want to pass it an image. If the parent can pass html/jsx to child then it can make the child render whatever it wants inside the child.

2023-06-14 09:22 UTC, omeryousaf commented on src/components/Modal/Modal.js
> +        <button onClick={props.handleModal}>Discard</button>
@Shapokhan let's change this prop name to onReject or sth else, sth that is more close to what this method will be used for ?

2023-06-21 06:42 UTC, omeryousaf commented on src/Feedback.js
> +          <img src={modalInfo.imageUrl} alt="Resource not found" />
👍

2023-06-21 06:49 UTC, omeryousaf commented on src/components/Modal/Modal.js
> +        <button onClick={props.handleModal}>Discard</button>
@Shapokhan **onReject** sounds too strong, how about **onCancel** ?

2023-06-21 07:02 UTC, omeryousaf commented on src/Feedback.js
> +          modalInfo={modalInfo}
@Shapokhan ye **modalInfo** Modal ko keun pass kar rahay ho ? wou tou isko use bhi nahin kar raha.

2023-06-21 07:07 UTC, omeryousaf submitted a review, later dismissed
@Shapokhan package-lock.json main changes keun aa rahi hain ?

2023-06-21 07:20 UTC, omeryousaf commented on src/Feedback.js
> +          onDiscard={onDiscard}
👍 `onDiscard` sounds good.

2023-06-21 07:21 UTC, omeryousaf commented on src/components/Modal/Modal.js
> +        <button onClick={props.onDiscard}>Discard</button>
👍 `onDiscard` sounds good inside a confirmation modal.

2023-06-21 07:25 UTC, omeryousaf requested changes
@Shapokhan this popup comes up even when there is no existing image that i'm replacing. It should not come up when there is no image being replaced.

2023-06-22 05:32 UTC, Shapokhan commented on src/Feedback.js
> +          modalInfo={modalInfo}
Removed.

2023-06-22 05:57 UTC, Shapokhan commented
> @Shapokhan this popup comes up even when there is no existing image that i'm replacing. It should not come up when there is no image being replaced.

Changes done. Now popup will only appear if there is an existing image.

2023-06-22 07:25 UTC, omeryousaf commented on src/components/Modal/Modal.module.css
> +  width: 500px;
@Shapokhan let's fix the image conatiner's dimensions so that the modal has the same height regradless of the input image.

2023-06-22 15:19 UTC, Shapokhan commented on src/components/Modal/Modal.module.css
> +  width: 500px;
@omeryousaf the required css changes have been applied. Can you please have a look and review this pull request. let me know if there is any changes need.

2023-06-22 15:58 UTC, Shapokhan commented
@omeryousaf can you please have a look at this pull request. The requested css changes, show pop up upon existing image (through paste and file change) have been made. Let me know if there is any changes required.

2023-07-02 09:05 UTC, omeryousaf approved these changes

2023-07-02 09:08 UTC, merged